### ISSUE TITLE
question about obj_nl in sca.py

### ISSUE THREAD

**Issue by zhuwenxing** [bmatthiesen/deep-EE-opt#2]
https://github.com/bmatthiesen/deep-EE-opt/blob/7089cb1646d13d169a100465626da61cb5609d17/src/SCA/sca.py#L98

Hi,
```python
obj_nl = cp.log(cp.multiply(np.diag(s) / tmp2, pvar) + 1) * txp
```
I konw that this means the expression in below and nl means nonlinear.

![image](https://user-images.githubusercontent.com/12268675/76401993-be3f2700-63bd-11ea-86e0-2fb2e0133c9f.png)
No offense! But, I think it should use ```np.diag(h)``` and will be 
```python
obj_nl = cp.log(cp.multiply(np.diag(h) / tmp2, pvar) + 1) * txp
```
Because if you use ```np.diag(s)```, numerator of SINR is already multiplied by p_i(a given point). However, you use cp.multiply() again.

I am not sure which one is correct.  If mine is incorrect, I hope you can explain it in more detail.

Thanks in advance.

**Comment by bmatthiesen** [comment]
Hi,

you're definitely right. That's a bad typo. We've corrected it in a3259fa135eab9c556fb187406df22e663d0cadf.

Thanks for finding and reporting it!

PS: In case you're planning to apply this algorithm to some problem and are interested in improving it, let me know and we can talk about it. I've a few ideas how to improve it...

**Comment by zhuwenxing** [comment]
Hi,
Yes!, I am working on a project that uses deep learning to solve EE max problem. So I need a traditional algorithm as a baseline. 

Here is another issue for the sca.py. You just set the noise power as a constant 1. I replace the 1 to a noise variable in expression calculating interference.  But I find when noise power is lower than 1, such as 0.1, the performance will not that satisfying. 

Since the sca.py can't run directly, I need to define h, Pmax,noise_power by myself, then call your SCA() function. So if you have free time, I hope you can modify the SCA() function to make noise as variable and add some tests(same as #1   I also have difficulty generating results.h5)! 

Thanks for your efforts!

**Comment by bmatthiesen** [comment]
Hi

> Here is another issue for the sca.py. You just set the noise power as a constant 1. I replace the 1 to a noise variable in expression calculating interference. But I find when noise power is lower than 1, such as 0.1, the performance will not that satisfying.

The performance of the whole algorithm is not overly satisfying. There are some improvements possible but in the end it's only a heuristic (although it has some convergence guarantees). If you want to discuss this further, please switch over to [email](mailto:matthiesen@uni-bremen.de).

As for the noise power, this is not an issue. You can always normalize the other variables such that the noise power is one. This is called the "standard form" of the interference channel and was first introduced in [Carleial1978](https://doi.org/10.1109/TIT.1978.1055812) (I think it's done for real-valued channels there. The extension to complex channels is trivial. See, e.g., page 99 in my [thesis](https://theses.eurasip.org/theses/853/efficient-globally-optimal-resource-allocation-in/).)

> Since the sca.py can't run directly, I need to define h, Pmax,noise_power by myself, then call your SCA() function. So if you have free time, I hope you can modify the SCA() function to make noise as variable and add some tests

Sorry to disappoint but that won't happen :). This is research code and, except for bug fixes, it will definitely stay in a form similar to when it was used to generate the numerical results in the paper.

**Comment by klb2** [comment]
> Since the sca.py can't run directly, I need to define h, Pmax,noise_power by myself, then call your SCA() function. So if you have free time, I hope you can modify the SCA() function to make noise as variable and add some tests(same as #1 I also have difficulty generating results.h5)!

We fixed the wrong paths in `src/DL/prepareDset.py` in 1b09c73.

Please note that it is not required to generate the data set on your own. We provide the files `data/dset4.h5` and `data/dset7.h5` for the four user and seven user scenario, respectively.

**Comment by zhuwenxing** [comment]
Get it! Thanks a lot!

> Hi
> 
> > Here is another issue for the sca.py. You just set the noise power as a constant 1. I replace the 1 to a noise variable in expression calculating interference. But I find when noise power is lower than 1, such as 0.1, the performance will not that satisfying.
> 
> The performance of the whole algorithm is not overly satisfying. There are some improvements possible but in the end it's only a heuristic (although it has some convergence guarantees). If you want to discuss this further, please switch over to [email](mailto:matthiesen@uni-bremen.de).
> 
> As for the noise power, this is not an issue. You can always normalize the other variables such that the noise power is one. This is called the "standard form" of the interference channel and was first introduced in [Carleial1978](https://doi.org/10.1109/TIT.1978.1055812) (I think it's done for real-valued channels there. The extension to complex channels is trivial. See, e.g., page 99 in my [thesis](https://theses.eurasip.org/theses/853/efficient-globally-optimal-resource-allocation-in/).)
> 
> > Since the sca.py can't run directly, I need to define h, Pmax,noise_power by myself, then call your SCA() function. So if you have free time, I hope you can modify the SCA() function to make noise as variable and add some tests
> 
> Sorry to disappoint but that won't happen :). This is research code and, except for bug fixes, it will definitely stay in a form similar to when it was used to generate the numerical results in the paper.

OK, I will check the reference you mentioned.

**Comment by zhuwenxing** [comment]
> > Since the sca.py can't run directly, I need to define h, Pmax,noise_power by myself, then call your SCA() function. So if you have free time, I hope you can modify the SCA() function to make noise as variable and add some tests(same as #1 I also have difficulty generating results.h5)!
> 
> We fixed the wrong paths in `src/DL/prepareDset.py` in [1b09c73](https://github.com/bmatthiesen/deep-EE-opt/commit/1b09c73ba4569cd30d95d691b0e7f913e4d368ad).
> 
> Please note that it is not required to generate the data set on your own. We provide the files `data/dset4.h5` and `data/dset7.h5` for the four user and seven user scenario, respectively.

Thanks, I will try to run it again!
